# Generated by Django 2.2.3 on 2019-08-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_order_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchievedOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Order')),
            ],
            options={
                'verbose_name': 'Архивированный заказ',
                'verbose_name_plural': 'Архивированные заказы',
            },
            bases=('main.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
    ]
