# Generated by Django 2.2.3 on 2019-08-11 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20190811_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archievedorder',
            name='order_ptr',
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_address',
            field=models.TextField(default=None, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_created_drinks',
            field=models.ManyToManyField(to='main.TempDrink'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='archieve_order_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_info',
            field=models.TextField(default=None, verbose_name='Инфо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_pizzas',
            field=models.ManyToManyField(to='main.TempPizza'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_presents',
            field=models.ManyToManyField(to='main.TempPresent'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_sauces',
            field=models.ManyToManyField(to='main.TempSauce'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_sets',
            field=models.ManyToManyField(to='main.TempSet'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_snacks',
            field=models.ManyToManyField(to='main.TempSnack'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.OrderState'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_title',
            field=models.CharField(default='', max_length=511, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='archievedorder',
            name='archieve_order_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
    ]
