# Generated by Django 2.2.3 on 2019-08-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20190811_1730'),
        ('main', '0047_auto_20190811_1722'),
    ]

    operations = [
    ]
