# Generated by Django 2.2.3 on 2019-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190720_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('volume', models.FloatField(default=0, verbose_name='Объём')),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.AddField(
            model_name='doughtype',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='topping',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('drinks', models.ManyToManyField(to='main.Drink')),
                ('pizzas', models.ManyToManyField(to='main.Pizza')),
                ('sauces', models.ManyToManyField(to='main.Sauce')),
                ('snacks', models.ManyToManyField(to='main.Snack')),
            ],
        ),
    ]
