# Generated by Django 2.2.3 on 2019-07-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pizzauser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaUser',
            new_name='AnonymousUser',
        ),
    ]
