# Generated by Django 2.2.3 on 2019-07-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190724_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususer',
            name='active',
        ),
        migrations.CreateModel(
            name='TempPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('doughType', models.ManyToManyField(to='main.DoughType')),
                ('size', models.ManyToManyField(to='main.Size')),
                ('toppings', models.ManyToManyField(to='main.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('cashback', models.PositiveIntegerField()),
                ('drinks', models.ManyToManyField(to='main.Drink')),
                ('pizzas', models.ManyToManyField(to='main.TempPizza')),
                ('sauces', models.ManyToManyField(to='main.Sauce')),
                ('snacks', models.ManyToManyField(to='main.Snack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AnonymousUser')),
            ],
        ),
    ]
