# Generated by Django 2.2.3 on 2019-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190724_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='drinks',
            field=models.ManyToManyField(blank=True, null=True, to='main.Drink'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='pizzas',
            field=models.ManyToManyField(blank=True, null=True, to='main.TempPizza'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='sauces',
            field=models.ManyToManyField(blank=True, null=True, to='main.Sauce'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='snacks',
            field=models.ManyToManyField(blank=True, null=True, to='main.Snack'),
        ),
    ]
