# Generated by Django 2.2.3 on 2019-07-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190724_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporder',
            name='cashback',
        ),
    ]
