# Generated by Django 2.2.3 on 2019-07-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_temporder_cashback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temppizza',
            name='active',
        ),
    ]
