# Generated by Django 2.2.3 on 2019-07-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_temppizza_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='drinks',
            field=models.ManyToManyField(to='main.Drink'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='pizzas',
            field=models.ManyToManyField(to='main.TempPizza'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='sauces',
            field=models.ManyToManyField(to='main.Sauce'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='snacks',
            field=models.ManyToManyField(to='main.Snack'),
        ),
        migrations.RemoveField(
            model_name='temppizza',
            name='doughType',
        ),
        migrations.AddField(
            model_name='temppizza',
            name='doughType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.DoughType'),
        ),
        migrations.RemoveField(
            model_name='temppizza',
            name='size',
        ),
        migrations.AddField(
            model_name='temppizza',
            name='size',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.Size'),
        ),
    ]
