# Generated by Django 2.2.3 on 2019-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190724_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='volume',
        ),
        migrations.AddField(
            model_name='drink',
            name='volume',
            field=models.ManyToManyField(to='main.Volume'),
        ),
    ]
