# Generated by Django 2.2.3 on 2019-07-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190724_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Volume')),
            ],
        ),
    ]
