# Generated by Django 2.2.3 on 2019-07-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tempdrink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='drinks',
            field=models.ManyToManyField(to='main.TempDrink'),
        ),
    ]
