# Generated by Django 2.2.3 on 2019-07-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190724_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='available',
            field=models.ManyToManyField(to='main.Size'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Размер', to='main.Size'),
        ),
    ]
