# Generated by Django 2.2.3 on 2019-07-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_priceforsize_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
    ]
