# Generated by Django 2.2.3 on 2019-07-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_pizza_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
