# Generated by Django 2.2.3 on 2019-07-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_pizza_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='volume',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
        migrations.AlterField(
            model_name='priceforsize',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Size'),
        ),
        migrations.CreateModel(
            name='PriceForVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('drink', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Drink')),
                ('volume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Volume')),
            ],
        ),
    ]
