# Generated by Django 2.2.3 on 2019-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_temporder_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='TempSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='TempSnack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='temporder',
            name='sauces',
            field=models.ManyToManyField(to='main.TempSet'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='sets',
            field=models.ManyToManyField(related_name='sets', to='main.TempSet'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='snacks',
            field=models.ManyToManyField(to='main.TempSnack'),
        ),
    ]
