# Generated by Django 2.2.3 on 2019-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_temppizza_elder_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='sauces',
            field=models.ManyToManyField(to='main.TempSauce'),
        ),
    ]
