# Generated by Django 2.2.3 on 2019-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_tempdrink_elder_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdrink',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='temppizza',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tempsauce',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tempset',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tempsnack',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
