# Generated by Django 2.2.3 on 2019-07-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190730_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='temppresent',
            name='picture',
        ),
    ]
