# Generated by Django 2.2.3 on 2019-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190730_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('description', models.TextField()),
            ],
        ),
    ]
