# Generated by Django 2.2.3 on 2019-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
