# Generated by Django 2.2.3 on 2019-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_discount_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.TextField(),
        ),
    ]
