# Generated by Django 2.2.3 on 2019-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190731_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('start', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('end', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('dinner_start', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('dinner_end', models.CharField(default='', max_length=511, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
