# Generated by Django 2.2.3 on 2019-08-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190802_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('cashback', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='anonymoususer',
            options={'verbose_name': 'Анонимный пользователь', 'verbose_name_plural': 'Анонимные пользователи'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Пост блога', 'verbose_name_plural': 'Посты блога'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='doughtype',
            options={'verbose_name': 'Тип теста для пицц', 'verbose_name_plural': 'Типы теста для пицц'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelOptions(
            name='present',
            options={'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
        migrations.AlterModelOptions(
            name='priceforsize',
            options={'verbose_name': 'Цена для размера пицц', 'verbose_name_plural': 'Цены для размеров пицц'},
        ),
        migrations.AlterModelOptions(
            name='priceforvolume',
            options={'verbose_name': 'Цена для объёма напитка', 'verbose_name_plural': 'Цены для объёмов напитков'},
        ),
        migrations.AlterModelOptions(
            name='sauce',
            options={'verbose_name': 'Соус', 'verbose_name_plural': 'Соусы'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'Сет', 'verbose_name_plural': 'Сеты'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер пиццы', 'verbose_name_plural': 'Размеры пиццы'},
        ),
        migrations.AlterModelOptions(
            name='snack',
            options={'verbose_name': 'Закуска', 'verbose_name_plural': 'Закуски'},
        ),
        migrations.AlterModelOptions(
            name='tempdrink',
            options={'verbose_name': 'Временный напиток', 'verbose_name_plural': 'Временные напитки'},
        ),
        migrations.AlterModelOptions(
            name='temporder',
            options={'verbose_name': 'Временный заказ', 'verbose_name_plural': 'Временные заказы'},
        ),
        migrations.AlterModelOptions(
            name='temppizza',
            options={'verbose_name': 'Временная пицца', 'verbose_name_plural': 'Временные пицца'},
        ),
        migrations.AlterModelOptions(
            name='temppresent',
            options={'verbose_name': 'Временный подарок', 'verbose_name_plural': 'Временные подарки'},
        ),
        migrations.AlterModelOptions(
            name='tempsauce',
            options={'verbose_name': 'Временный соус', 'verbose_name_plural': 'Временные соусы'},
        ),
        migrations.AlterModelOptions(
            name='tempset',
            options={'verbose_name': 'Временный сет', 'verbose_name_plural': 'Временные сеты'},
        ),
        migrations.AlterModelOptions(
            name='tempsnack',
            options={'verbose_name': 'Временная закуска', 'verbose_name_plural': 'Временные закуски'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'Топпинг', 'verbose_name_plural': 'Топпинги'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Объём', 'verbose_name_plural': 'Объёмы'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default='', verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='show_body',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='doughtype',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='available',
            field=models.ManyToManyField(to='main.Volume', verbose_name='Доступные объёмы'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='available',
            field=models.ManyToManyField(to='main.Size', verbose_name='Доступные размеры'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='doughType',
            field=models.ManyToManyField(to='main.DoughType', verbose_name='Тип теста'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='main.Topping', verbose_name='Топпинги'),
        ),
        migrations.AlterField(
            model_name='present',
            name='title',
            field=models.CharField(default='', max_length=511, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='priceforsize',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Pizza', verbose_name='Пицца'),
        ),
        migrations.AlterField(
            model_name='priceforsize',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='priceforvolume',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Drink', verbose_name='Напиток'),
        ),
        migrations.AlterField(
            model_name='priceforvolume',
            name='volume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Volume', verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='set',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='set',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='title',
            field=models.CharField(default='', max_length=511, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='temppresent',
            name='title',
            field=models.CharField(default='', max_length=511, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(default='', max_length=511, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('drinks', models.ManyToManyField(to='main.TempDrink')),
                ('pizzas', models.ManyToManyField(to='main.TempPizza')),
                ('presents', models.ManyToManyField(to='main.TempPresent')),
                ('sauces', models.ManyToManyField(to='main.TempSauce')),
                ('sets', models.ManyToManyField(to='main.TempSet')),
                ('snacks', models.ManyToManyField(to='main.TempSnack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name': 'Временный заказ',
                'verbose_name_plural': 'Временные заказы',
            },
        ),
    ]
