# Generated by Django 2.2.3 on 2019-08-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190806_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Состояние заказа',
                'verbose_name_plural': 'Состояния заказа',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.OrderState'),
        ),
    ]
