# Generated by Django 2.2.3 on 2019-08-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20190807_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.AnonymousUser'),
            preserve_default=False,
        ),
    ]
