# Generated by Django 2.2.3 on 2019-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_user_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=None, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.TextField(default=None, verbose_name='Инфо'),
            preserve_default=False,
        ),
    ]
