# Generated by Django 2.2.3 on 2019-08-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20190809_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Актуально'),
        ),
    ]
