# Generated by Django 2.2.3 on 2019-08-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190809_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото для слайдера',
                'verbose_name_plural': 'Фото для слайдера',
            },
        ),
    ]
