# Generated by Django 2.2.3 on 2019-08-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_headerimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderImages',
            new_name='HeaderImage',
        ),
    ]
