# Generated by Django 2.2.3 on 2019-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190809_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMobileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото для мобильного Header',
                'verbose_name_plural': 'Фото для мобильного Header',
            },
        ),
    ]
