# Generated by Django 2.2.3 on 2019-08-11 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.CreateModel(
            name='ArchievedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=511, verbose_name='Название')),
                ('address', models.TextField(default='', verbose_name='Адрес')),
                ('info', models.TextField(default='', verbose_name='Инфо')),
                ('active', models.BooleanField(default=False, verbose_name='Актуально')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('drinks', models.ManyToManyField(to='main.TempDrink')),
                ('pizzas', models.ManyToManyField(to='main.TempPizza')),
                ('presents', models.ManyToManyField(to='main.TempPresent')),
                ('sauces', models.ManyToManyField(to='main.TempSauce')),
                ('sets', models.ManyToManyField(to='main.TempSet')),
                ('snacks', models.ManyToManyField(to='main.TempSnack')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.OrderState')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'verbose_name': 'Архивированный заказ',
                'verbose_name_plural': 'Архивированные заказы',
            },
        ),
    ]
