# Generated by Django 2.2.3 on 2019-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20190811_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
